version: "3.9"
networks:
  default:
    driver: bridge
services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: programming-school
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app: 
    container_name: programming-school
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - default
    depends_on:
      - postgres_db
  front:
    container_name: programming-school-front
    build:
      context: .
      dockerfile: ./programming-school/Dockerfile
    ports:
      - "81:81"
    expose:
      - "81"
    networks:
      - default
    depends_on:
      - app
volumes:
  postgres-data: